### ISSUE TITLE
Put colour blind theme options in an `optgroup` tag

### ISSUE THREAD

**Issue by Shrinks99** [hyphacoop/reader.distributed.press#16]
Colour blind themes are great to support!  Menu options that can be selected but do nothing are less great.

The ideal way to do this is to use an `<optgroup>` tag to group the `<option>` tags together!  This will also be read correctly by screen readers.

My intrim recommendation would be to remove the `👁️ Color Blind Themes 👁️` option entirely.

**Comment by akhileshthite** [comment]
> Colour blind themes are great to support! Menu options that can be selected but do nothing are less great.
> 
> The ideal way to do this is to use an `<optgroup>` tag to group the `<option>` tags together! This will also be read correctly by screen readers.
> 
> My intrim recommendation would be to remove the `👁️ Color Blind Themes 👁️` option entirely.

Thanks for your suggestion!

**Comment by akhileshthite** [comment]
#19 Done
