### ISSUE TITLE
In social reader, description shows the "<p>" opening and closing html element + image doesn't allow opening in full

### ISSUE THREAD

**Issue by edumerco** [hyphacoop/reader.distributed.press#23]
Looking at my account through the social reader, I see 2 things to review (see screen capture):
![social-reader-2bugs](https://github.com/hyphacoop/reader.distributed.press/assets/1304807/284c4aae-736e-4e06-b279-fd116382b412)

1. the paragraph html element shows around the description. 
2. the image is not clickable to see it in full.

**Comment by akhileshthite** [comment]
> Looking at my account through the social reader, I see 2 things to review (see screen capture): ![social-reader-2bugs](https://private-user-images.githubusercontent.com/1304807/347506178-284c4aae-736e-4e06-b279-fd116382b412.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjA2OTc0NDksIm5iZiI6MTcyMDY5NzE0OSwicGF0aCI6Ii8xMzA0ODA3LzM0NzUwNjE3OC0yODRjNGFhZS03MzZlLTRlMDYtYjI3OS1mZDExNjM4MmI0MTIucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDcxMSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA3MTFUMTEyNTQ5WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MTdiMmY2NDJmZGViOGMyMmMzMmE5YjhjM2I0MTM5MjQ5ZjY1MmExNTQxYzlmNGZhZDVmYWJkZWFmODAwZWVkMSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.iCQPrODU9T0NgQxaAwO5SAI5XS1RyN9_SusfE4q_R2Q)
> 
> 1. the paragraph html element shows around the description.
> 2. the image is not clickable to see it in full.

Hey,
Yep it's because we're using the `.textContent` instead of `.innerHTML` to load the profile summary, will push the changes in few hours.

Regarding the profile image, we haven't implemented such functionality yet. Right now, you can click on the username `@edumerco` and it will open the mastodon profile page, you can view the profile image in full size there.

Personally, if I'm using the social reader on my phone, I would zoom in on the page or click on it until my browser opens a new full-size popup. On the web, I would just click on it and drag and drop it on my desktop window to see it.

> Even Instagram released this feature to view profile images last year, after 13 years!

Thanks

**Comment by edumerco** [comment]
Ah, great (I'm from Sutty, I don't know if you remember me), so that point will be fixed. 
Are you planning something about the images? 

Best... :)

**Comment by akhileshthite** [comment]
> Ah, great (I'm from Sutty, I don't know if you remember me), so that point will be fixed. Are you planning something about the images?
> 
> Best... :)

Yes, I remember :D

Currently we're working on replies for the social reader: https://github.com/hyphacoop/distributed-press-organizing/issues/129

Will keep this issue open to work on viewing profile images in full-size in the future
Thanks

**Comment by edumerco** [comment]
Beautiful!
Thanks a lot. :)

Best...

15 jul. 2024 10:18:49 Akhilesh Thite ***@***.***>:

**Comment by akhileshthite** [comment]
Done
https://github.com/hyphacoop/reader.distributed.press/commit/44bd32da9e0238ada6a0d11c8f4c7eb39857643f

**Comment by edumerco** [comment]
>  Done
>  44bd32d

Thanks! :)

Best...


-- 
eduardo mercovich

 Donde se cruzan tus talentos 
 con las necesidades del mundo, 
 ahí está tu vocación. 
 (Anónimo)
